"""unique route per source-destination

Revision ID: 59a7eeee409b
Revises: 804043020edc
Create Date: 2026-06-18 00:57:16.599219

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '59a7eeee409b'
down_revision: Union[str, Sequence[str], None] = '804043020edc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_routes_source_destination', 'routes', ['source_id', 'destination_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_routes_source_destination', 'routes', type_='unique')
    # ### end Alembic commands ###
