"""delivery_lock_mechanism

Revision ID: d850b2459594
Revises: 59a7eeee409b
Create Date: 2026-07-02 14:56:07.029813

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd850b2459594'
down_revision: Union[str, Sequence[str], None] = '59a7eeee409b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('deliveries', sa.Column('locked_by', sa.Uuid(), nullable=True))
    op.add_column('deliveries', sa.Column('locked_until', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('deliveries', 'locked_until')
    op.drop_column('deliveries', 'locked_by')
    # ### end Alembic commands ###
